name: Nettoyeur J+1 (Historique)

on:
  schedule:
    - cron: '0 4 * * *' # Tous les jours à 4h00 du matin UTC
  workflow_dispatch: # Permet le lancement manuel via un bouton

jobs:
  nettoyage:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install -r requirements.txt

      - name: Création du fichier de Secrets
        run: |
          mkdir -p .streamlit
          echo "OPENSKY_USER = '${{ secrets.OPENSKY_USER }}'" > .streamlit/secrets.toml
          echo 'OPENSKY_PWD = "${{ secrets.OPENSKY_PWD }}"' >> .streamlit/secrets.toml
          echo "${{ secrets.GCP_SERVICE_ACCOUNT }}" >> .streamlit/secrets.toml

      - name: Lancement du Nettoyage Historique
        run: python cleaner_j1.py
