name: Radar Joinville-le-Pont

on:
  schedule:
    - cron: '*/2 * * * *' # Toutes les 2 minutes
  workflow_dispatch: # Permet le lancement manuel et via un bouton

jobs:
  surveillance:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          pip install -r requirements.txt

      - name: Cache de la base aircraft_db
        uses: actions/cache@v4
        with:
          path: aircraft_db.parquet
          key: aircraft-db-${{ github.run_id }}
          restore-keys: |
            aircraft-db-

      - name: Création du fichier de Secrets
        run: |
          mkdir -p .streamlit
          cat <<EOF > .streamlit/secrets.toml
          OPENSKY_USER = "${{ secrets.OPENSKY_USER }}"
          OPENSKY_PWD = "${{ secrets.OPENSKY_PWD }}"
          
          [connections.gsheets]
          ${{ secrets.GCP_SERVICE_ACCOUNT }}
          EOF

      - name: Lancement du Radar
        run: python collector.py
